soft-fail: false
quiet: true
compact: true
framework:
  - all
skip-check:
  - CKV_K8S_21  # Default namespace usage
  - CKV_K8S_43  # Image tag validation (using latest tags intentionally)
  - CKV_K8S_14  # Image tag should be fixed (same as above)
  - CKV_K8S_22  # Read-only filesystem (IRC apps need to write to volumes)
  - CKV_K8S_40  # Containers should run as high UID (ZNC LinuxServer container needs flexibility)
