soft-fail: false
quiet: true
compact: true
framework:
  - all
skip-check:
  - CKV_K8S_21 # Default namespace usage
  - CKV_K8S_43 # Image tag validation
  - CKV_K8S_40 # High UID requirement
  - CKV_K8S_29 # Security context
  - CKV_K8S_23 # Root containers
  - CKV_K8S_37 # Container capabilities
  - CKV_K8S_22 # Read-only filesystem
  - CKV_K8S_28 # NET_RAW capability
  - CKV_K8S_31 # Seccomp profile
  - CKV_K8S_14 # Image tag should be fixed
