## StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: znc
  annotations:
    polaris.fairwinds.com/runAsRootAllowed-exempt: "true" # linuxserver.io images don't support this, need to build my own
    polaris.fairwinds.com/tagNotSpecified-exempt: "true" # allow latest tag for this app
    polaris.fairwinds.com/topologySpreadConstraint-exempt: "true" # statefulset doesn't support multiple replicas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: znc
  serviceName: "znc"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: znc
        app.kubernetes.io/instance: znc
    spec:
      priorityClassName: low-priority
      automountServiceAccountToken: false
      containers:
      - name: znc
        image: lscr.io/linuxserver/znc:latest    
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 6501
          name: irc-6501
        volumeMounts:
        - name: config
          mountPath: "/app/config"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
